### PR TITLE
FIXED add method set_state in Package

### PR DESCRIPTION
**Pull request by earandap**
check this

### CODE REVIEW

**Comment by elin3t** [comment]
In this one I think the method isnt only set_state, but set_state and calculate_state is needed, to check the current state without to set_it and calculate it in all the itinerary and package update

**Comment by earandap** [comment]
This method is useful for OrderService when need update the state of package, for example dispatch a package. After that Order can calculate the state because only need read the states of the packages.

**Comment by pauriarte** [comment]
+1

**Comment by elin3t** [comment]
+1

**Pull request merged**
